const sceneryList = [
  {
    id: 1,
    name: "回忆之丘",
    desc: "艾恩格朗特47层南侧野外迷宫",
    tags: ["休闲娱乐", "复活"],
    type: 2,
    time: "3h",
    score: 5,
    price: 10,
    image: "preview.png",
  },
  {
    id: 2,
    name: "西边山脉",
    desc: "艾恩格朗特55层，吞食水晶的魔龙出没，占位符占位符占位符占位符占位符占位符占位符占位符占位符占位符",
    tags: ["亲子出行", "锻造材料"],
    type: 1,
    time: "8h",
    score: 4,
    price: 50,
    image: "preview.png",
  },
  {
    id: 3,
    name: "森之屋",
    desc: "艾恩格朗特22层南部高拉尔村外围",
    tags: ["曲径探幽"],
    type: 3,
    time: "3h",
    score: 5,
    price: 0,
    image: "preview.png",
  },
  {
    id: 4,
    name: "塞尔穆布鲁克",
    desc: "艾恩格朗特61层中心市区",
    tags: ["休闲娱乐", "居家"],
    type: 2,
    time: "3h",
    score: 5,
    price: 10,
    image: "preview.png",
  },
  {
    id: 5,
    name: "莉兹贝特武器店",
    desc: "艾恩格朗特48层主街区琳达司",
    tags: ["休闲娱乐", "锻造"],
    type: 2,
    time: "3h",
    score: 5,
    price: 20,
    image: "preview.png",
  },
]

module.exports = {
  sceneryList
}