### Loaded
import os
import json
import pandas as pd

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

with open(BASE_DIR + '/adcode.json', 'r', encoding='utf8') as f:
    ADCODE = json.load(f)
ADCODE_DF = pd.read_csv(BASE_DIR + '/adcode.csv')

### App
# 这部分如果小程序没发布的话好像没什么左右（逃）
APPID = 'wxd3b8c5438a79609d'
APPSECRET = 'ab2dc811bb5f830308d66ff489b049eb'
OPENID_LEN = 128
SERVER_IP = '114.116.53.144'
SERVER_HOSTNAME = 'tra-fr-2.zhouyc.cc'
SERVER_PORT = 443

APP_SHOW_STATUS = True

### Utilities
## UUID
DEFAULT_NAMESPACE = 'db5acd0b317f474f82d0294722786034'
IMAGE_NAMESPACE = '04814d8c269b465cab37423163984ba0'

## JWT
JWT_EXPIRE_SECONDS = 60 * 60 * 24

## Permission
SUPER_USER_ID = -2
ADMIN_USER_ID = -1
ANONYMOUS_USER_ID = 0
USER_JWT_HEADER_NAME = 'token-auth'
USER_JWT_KEY = '958bfcfd62d236249b443a2283b0c51a'

### Admin
ADMIN_USERNAME = 'web'
ADMIN_PASSWORD = 'dwOftI4yo8J22614'
ADMIN_ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjozMjUzNjg1MDM5OSwianRpIjoiVGhpcyB0b2tlbiBpcyBtYW51YWxseSBjcmVhdGVkLiIsInVzZXJfaWQiOjF9.4Xne0Jk3n_wUYIiDPHKLjj69RoXEKcx5fOTWk3xRSe0'

### App
## Models
# Images
MAX_IMAGE_DESCRIPTION_LEN = 200

# Recommend
RECOMMEND_DECAY_PARAM1 = -0.27621943
RECOMMEND_DECAY_PARAM2 = -0.91748966

RECOMMEND_LIKE_AMOUNT = 100

RECOMMEND_PCA_DIMENSIONS = 16
RECOMMEND_CLUSTER_RATIO = 0.0001
RECOMMEND_CLUSTER_MINIMUM = 8

# AppUser
MAX_USER_NAME_LEN = 20
MAX_USER_REALNAME_LEN = 10
MAX_USER_SIGN_LEN = 140
MAX_USER_PASSWORD_LEN = 64
MAX_USER_EMAIL_LEN = 40
MAX_USER_PHONE_LEN = 30

USER_ID_NAMESPACE = '2318d637c663305c8cd06f6144c60b01'

GENDERS = {
    0: 'Unknown',
    1: 'Male',
    2: 'Female',
}
GENDERS_DEFAULT = 0

# Position
COUNTRIES = {
    0: '',
}
COUNTRIES_DEFAULT = 0

PROVINCES = {
    0: '',
}
PROVINCES_DEFAULT = 0

CITIES = {
    0: '',
}
CITIES_DEFAULT = 0

DISTRICTS = {
    0: '',
}
DISTRICTS_DEFAULT = 0

MAX_POSITION_POSTAL_CODE_LENGTH = 6

POSITION_RECOMMEND_AMOUNT = 3
POSITION_RECOMMEND_MAX_AMOUNT = 20
POSITION_RECOMMEND_TRUNCATE = 16

# Travel
MAX_TRAVEL_TITLE_LENGTH = 40
MAX_TRAVEL_CONTENT_LENGTH = 20000

TRAVEL_VISIBILITIES_ALL = 0
TRAVEL_VISIBILITIES_PRIVATE = 1

TRAVEL_VISIBILITIES = {
    TRAVEL_VISIBILITIES_ALL: 'All',
    TRAVEL_VISIBILITIES_PRIVATE: 'Private',
}
TRAVEL_VISIBILITIES_DEFAULT = 0

TRAVEL_FORBIDDEN_FALSE = 0
TRAVEL_FORBIDDEN_TRUE = 1
TRAVEL_FORBIDDEN_PENDING = 2

TRAVEL_LIST_MODE_TIME = 0
TRAVEL_LIST_MODE_HEAT = 1
TRAVEL_LIST_MODE_RECOMMEND = 2

TRAVEL_LIST_MODES = {
    TRAVEL_LIST_MODE_TIME,
    TRAVEL_LIST_MODE_HEAT,
    TRAVEL_LIST_MODE_RECOMMEND,
}
TRAVEL_LIST_MODE_DEFAULT = TRAVEL_LIST_MODE_TIME

TRAVEL_HEAT_READ_RECORD = 30

TRAVEL_HEAT_WEIGHT_RECENT = 1
TRAVEL_HEAT_WEIGHT_COLLECTIONS = 50
TRAVEL_HEAT_WEIGHT_LIKES = 10
TRAVEL_HEAT_WEIGHT_COMMENTS = 100

TRAVEL_RECOMMEND_DEFAULT_AMOUNT = 20
TRAVEL_RECOMMEND_MAX_AMOUNT = 20

TRAVEL_RECOMMEND_EXCEED_RATE = 2.0
TRAVEL_RECOMMEND_CLUSTER_WEIGHT = 0.6
TRAVEL_RECOMMEND_USER_WEIGHT = 0.3
TRAVEL_RECOMMEND_HEAT_WEIGHT = 0.1

TRAVEL_SIMILAR_AMOUNT = 3
TRAVEL_SIMILAR_MAX_AMOUNT = 20

# Comment
MAX_COMMENT_CONTENT_LENGTH = 400
COMMENT_TYPE_TRAVEL = 0
COMMENT_TYPE_COMPANION = 1
COMMENT_TYPE_SIGHT = 2

COMMENT_DELETED_CONTENT = '该评论已删除'

# Message
MAX_MESSAGE_CONTENT_LENGTH = 400

MESSAGE_TYPE_SYSTEM = 0
MESSAGE_TYPE_LIKE_TRAVEL = 1
MESSAGE_TYPE_LIKE_COMMENT = 2
MESSAGE_TYPE_SUBSCRIBE = 3
MESSAGE_TYPE_COMMENT_ON_TRAVEL = 4
MESSAGE_TYPE_COMMENT_ON_COMMENT = 5
MESSAGE_TYPE_COMPANION = 6
MESSAGE_TYPE_COMPANION_QUIT = 7
MESSAGE_TYPE_COMMENT_ON_SIGHT = 8

MESSAGE_TYPE_TRAVEL_FORBIDDEN = 20
MESSAGE_TYPE_COMPANION_FORBIDDEN = 21
MESSAGE_TYPE_TRAVEL_FORBIDDEN_CANCEL = 22
MESSAGE_TYPE_COMPANION_FORBIDDEN_CANCEL = 23
MESSAGE_TYPE_SCHEDULE_NOTIFY = 40
MESSAGE_TYPE_FLIGHT_NOTIFY = 41

MESSAGE_UNIQUE = {
    MESSAGE_TYPE_LIKE_TRAVEL,
    MESSAGE_TYPE_LIKE_COMMENT,
    MESSAGE_TYPE_SUBSCRIBE,
}

MESSAGE_TYPES_DESCRIPTION = {
    MESSAGE_TYPE_SYSTEM: '有新的通知',
    MESSAGE_TYPE_LIKE_TRAVEL: '点赞了你的游记',
    MESSAGE_TYPE_LIKE_COMMENT: '点赞了你的评论',
    MESSAGE_TYPE_SUBSCRIBE: '关注了你',
    MESSAGE_TYPE_COMMENT_ON_TRAVEL: '评论了你的游记',
    MESSAGE_TYPE_COMMENT_ON_COMMENT: '回复了你',
    MESSAGE_TYPE_COMPANION: '加入了你的同行',
    MESSAGE_TYPE_COMPANION_QUIT: '退出了你的同行',
    MESSAGE_TYPE_TRAVEL_FORBIDDEN: '你的游记未通过审核',
    MESSAGE_TYPE_COMPANION_FORBIDDEN: '你的同行未通过审核',
    MESSAGE_TYPE_TRAVEL_FORBIDDEN_CANCEL: '你的游记已通过审核',
    MESSAGE_TYPE_COMPANION_FORBIDDEN_CANCEL: '你的同行已通过审核',
    MESSAGE_TYPE_SCHEDULE_NOTIFY: '你有尚未完成的日程',
    MESSAGE_TYPE_FLIGHT_NOTIFY: '你关注的航班即将起飞',
}
MESSAGE_TYPES_DEFAULT = MESSAGE_TYPE_SYSTEM

# Companion
COMPANION_STATUS_RECRUITING = 0
COMPANION_STATUS_END_RECRUIT = 1
COMPANION_STATUS_STARTED = 2
COMPANION_STATUS_ENDED = 3

COMPANION_REMOVABLE_TIME = 86400 * 3  # 3 days

COMPANION_MAX_CAPACITY = 10000

COMPANION_RECOMMEND_AMOUNT = 3
COMPANION_RECOMMEND_MAX_AMOUNT = 20

# Admin Message
ADMIN_MESSAGE_TIME_LIMIT = 86400

# Flight
MAX_FLIGHT_NO_LEN = 12
MAX_FLIGHT_AIRLINE_LEN = 12

FLIGHT_LIST_MODE_DEPART_TIME_UP = 0
FLIGHT_LIST_MODE_DEPART_TIME_DOWN = 1
FLIGHT_LIST_MODE_ECONOMY_MINPRICE_UP = 2
FLIGHT_LIST_MODE_ECONOMY_MINPRICE_DOWN = 3
FLIGHT_LIST_MODE_BUSINESS_MINPRICE_UP = 4
FLIGHT_LIST_MODE_BUSINESS_MINPRICE_DOWN = 5
FLIGHT_LIST_MODE_ECONOMY_DISCOUNT_UP = 6
FLIGHT_LIST_MODE_ECONOMY_DISCOUNT_DOWN = 7
FLIGHT_LIST_MODE_BUSINESS_DISCOUNT_UP = 8
FLIGHT_LIST_MODE_BUSINESS_DISCOUNT_DOWN = 9
FLIGHT_LIST_MODE_COST_TIME_UP = 10
FLIGHT_LIST_MODE_COST_TIME_DOWN = 11

FLIGHT_LIST_MODES = {
    FLIGHT_LIST_MODE_DEPART_TIME_UP,
    FLIGHT_LIST_MODE_DEPART_TIME_DOWN,
    FLIGHT_LIST_MODE_ECONOMY_MINPRICE_UP,
    FLIGHT_LIST_MODE_ECONOMY_MINPRICE_DOWN,
    FLIGHT_LIST_MODE_BUSINESS_MINPRICE_UP,
    FLIGHT_LIST_MODE_BUSINESS_MINPRICE_DOWN,
    FLIGHT_LIST_MODE_ECONOMY_DISCOUNT_UP,
    FLIGHT_LIST_MODE_ECONOMY_DISCOUNT_DOWN,
    FLIGHT_LIST_MODE_BUSINESS_DISCOUNT_UP,
    FLIGHT_LIST_MODE_BUSINESS_DISCOUNT_DOWN,
    FLIGHT_LIST_MODE_COST_TIME_UP,
    FLIGHT_LIST_MODE_COST_TIME_DOWN,
}
FLIGHT_LIST_MODE_DEFAULT = FLIGHT_LIST_MODE_DEPART_TIME_UP

FLIGHT_TRANS_LIST_MODE_DEPART_COST_UP = 0
FLIGHT_TRANS_LIST_MODE_DEPART_TOTAL_TIME_UP = 1
FLIGHT_TRANS_LIST_MODES = {
    FLIGHT_TRANS_LIST_MODE_DEPART_COST_UP,
    FLIGHT_TRANS_LIST_MODE_DEPART_TOTAL_TIME_UP,
}
FLIGHT_TRANS_LIST_MODE_DEFAULT = FLIGHT_TRANS_LIST_MODE_DEPART_COST_UP

FLIGHT_STATUS_NORMAL = 0
FLIGHT_STATUS_LATE = 1
FLIGHT_STATUS_EARLY = 2
FLIGHT_STATUS_ABNORMAL = 3
FLIGHT_STATUS_DEFAULT = FLIGHT_STATUS_NORMAL

# UsersFlight
FLIGHT_ALARM_FALSE = 0
FLIGHT_ALARM_TRUE = 1

USERS_FLIGHT_UNFOLLOW = 0
USERS_FLIGHT_FOLLOW = 1
USERS_FLIGHT_ALARM_FALSE = FLIGHT_ALARM_FALSE
USERS_FLIGHT_ALARM_TRUE = FLIGHT_ALARM_TRUE

# Port
MAX_PORT_CODE_LEN = 6
MAX_PORT_NAME_LEN = 12

# Schedule
MAX_SCHEDULEITEM_CONTENT_LENGTH = 1000
MAX_SCHEDULE_REMARKS_LENGTH = 2000
MAX_SCHEDULE_TITLE_LENGTH = 48

SCHEDULE_FORBIDDEN_FALSE = 0
SCHEDULE_FORBIDDEN_TRUE = 1
SCHEDULE_FORBIDDEN_PENDING = 2

SCHEDULE_VISIBILITIES_ALL = 0
SCHEDULE_VISIBILITIES_PRIVATE = 1
SCHEDULE_VISIBILITIES_DEFAULT = SCHEDULE_VISIBILITIES_PRIVATE

SCHEDULE_ALARM_FALSE = 0
SCHEDULE_ALARM_TRUE = 1

SCHEDULE_ALARM_LIST = [
    SCHEDULE_ALARM_FALSE,
    SCHEDULE_ALARM_TRUE
]

SCHEDULE_COPY_COVER = 0
SCHEDULE_COPY_MERGE = 1
SCHEDULE_COPY_DEFAULT = SCHEDULE_COPY_COVER

# Tag
MAX_TAG_NAME_LEN = 48

# TravelCollection
MAX_TC_TITLE_LENGTH = 48
DEFAULT_TITLE_NAME = '默认合集'

# City
MAX_CITY_NAME_LEN = 8

# Province
MAX_PROVINCE_NAME_LEN = 8

# Log
LOG_USER_REGISTER = 100
LOG_USER_LOGIN = 101
LOG_TRAVEL_CREATE = 200
LOG_TRAVEL_EDIT = 201
LOG_TRAVEL_DELETE = 202
LOG_TRAVEL_VIEW = 203
LOG_TRAVEL_LIKE = 204
LOG_TRAVEL_LIKE_CANCEL = 214
LOG_TRAVEL_COLLECT = 205
LOG_COMPANION_CREATE = 300
LOG_COMPANION_EDIT = 301
LOG_COMPANION_DELETE = 302
LOG_COMPANION_ADD = 303
LOG_COMPANION_QUIT = 304
LOG_COMPANION_VIEW = 305
LOG_TRAVELCOLLECTION_CREATE = 400
LOG_TRAVELCOLLECTION_EDIT = 401
LOG_TRAVELCOLLECTION_DELETE = 402
LOG_FLIGHT_VIEW = 500
LOG_FLIGHT_FOLLOW = 501
LOG_FLIGHT_FOLLOW_CANCEL = 502
LOG_SCHEDULE_CREATE = 600
LOG_SCHEDULE_EDIT = 601
LOG_SCHEDULE_DELETE = 602
LOG_SCHEDULE_VIEW = 603
LOG_SCHEDULE_COPY = 604
LOG_COMMENT_CREATE = 700
LOG_COMMENT_EDIT = 701
LOG_COMMENT_DELETE = 702
LOG_ACTION_LIST = [
    LOG_USER_REGISTER,
    LOG_USER_LOGIN,
    LOG_TRAVEL_CREATE,
    LOG_TRAVEL_EDIT,
    LOG_TRAVEL_DELETE,
    LOG_TRAVEL_VIEW,
    LOG_TRAVEL_LIKE,
    LOG_TRAVEL_LIKE_CANCEL,
    LOG_TRAVEL_COLLECT,
    LOG_COMPANION_CREATE,
    LOG_COMPANION_EDIT,
    LOG_COMPANION_DELETE,
    LOG_COMPANION_ADD,
    LOG_COMPANION_QUIT,
    LOG_COMPANION_VIEW,
    LOG_TRAVELCOLLECTION_CREATE,
    LOG_TRAVELCOLLECTION_EDIT,
    LOG_TRAVELCOLLECTION_DELETE,
    LOG_FLIGHT_VIEW,
    LOG_FLIGHT_FOLLOW,
    LOG_FLIGHT_FOLLOW_CANCEL,
    LOG_SCHEDULE_CREATE,
    LOG_SCHEDULE_EDIT,
    LOG_SCHEDULE_DELETE,
    LOG_SCHEDULE_VIEW,
    LOG_SCHEDULE_COPY,
    LOG_COMMENT_CREATE,
    LOG_COMMENT_EDIT,
    LOG_COMMENT_DELETE
]

MAX_REMARKS_LEN = 48

# shielded words
MAX_SHIELDED_WORDS_LEN = 24

# sight
MAX_SIGHT_NAME_LEN = 32

# inner_sight
MAX_SUBSIGHT_NAME_LEN = 16

# price
MAX_PRICE_TYPE_LEN = 32

# sight type
SIGHT_TYPE_CHOICE = [
    (1, '亲子出行'),
    (2, '休闲娱乐'),
    (3, '人文景观'),
    (4, '全部景点')
]

# feedback
FEEDBACK_TYPE = [
    (0, '一般反馈'),
    (1, '景点添加'),
    (2, '景点修改')
]
FEEDBACK_STATUS = (
        (0, 'Draft'),
        (1, 'Approve'),
        (2, 'Reject'),
    )

# travel_tag_query
TAG_QUERY_ORDER_BY_TIME_UP = 0
TAG_QUERY_ORDER_BY_TIME_DOWN = 1
TAG_QUERY_ORDER_BY_REC = 2
TAG_QUERY_ORDER_BY_DEFAULT = TAG_QUERY_ORDER_BY_REC


TAGS = pd.read_csv(BASE_DIR + '/tag.csv', encoding='GBK')
