# Generated by Django 4.1.7 on 2023-04-02 04:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import utils.date
import utils.encrypt
import utils.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('nation', models.CharField(blank=True, default='', max_length=32)),
                ('province', models.CharField(blank=True, default='', max_length=32)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('district', models.CharField(blank=True, default='', max_length=32)),
                ('street', models.CharField(blank=True, default='', max_length=32)),
                ('street_number', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('openid', models.CharField(max_length=128, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=10)),
                ('gender', models.IntegerField(default=0)),
                ('sign', models.CharField(blank=True, default='', max_length=140)),
                ('email', models.CharField(blank=True, default='', max_length=40)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('birthday', models.DateField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(default=utils.date.now)),
                ('cluster', models.PositiveIntegerField(default=0)),
                ('last_admin_message_time', models.DateTimeField(default=utils.date.now)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='', max_length=400)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('title', models.TextField(default='', max_length=40)),
                ('content', models.TextField(default='', max_length=20000)),
                ('private_content', models.TextField(default='')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('forbidden', models.IntegerField(default=0)),
                ('forbidden_reason', models.TextField(default='')),
                ('cancelled_users', models.ManyToManyField(related_name='cancelled_companions', to='utility.appuser')),
                ('fellows', models.ManyToManyField(related_name='joined_companions', to='utility.appuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='companions', to='utility.appuser')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion', to='utility.address')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(blank=True, default='', max_length=12)),
                ('airline', models.CharField(blank=True, default='', max_length=12)),
                ('economy_minprice', models.FloatField(null=True)),
                ('economy_discount', models.FloatField(null=True)),
                ('bussiness_minprice', models.FloatField(null=True)),
                ('bussiness_discount', models.FloatField(null=True)),
                ('food', models.BooleanField(null=True)),
                ('depart_time', models.DateTimeField()),
                ('cost_time', models.TimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=functools.partial(utils.encrypt.random_id, *(), **{'len': 32}), max_length=32, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to=utils.uuid.on_upload_rename('images'))),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=6)),
                ('name', models.CharField(blank=True, default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('title', models.TextField(max_length=2000)),
                ('remarks', models.TextField(default=None, max_length=2000, null=True)),
                ('visibility', models.IntegerField(default=1)),
                ('forbidden', models.IntegerField(default=0)),
                ('forbidden_reason', models.TextField(default='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule_records', to='utility.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='ShieldedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=48, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TravelCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(max_length=48)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_travelcollections', to='utility.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UsersFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_alarm', models.IntegerField(default=0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_to_user', to='utility.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_flight', to='utility.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='TravelNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(default='', max_length=40)),
                ('content', models.TextField(blank=True, default='', max_length=20000)),
                ('read_total', models.IntegerField(default=0)),
                ('last_read', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.IntegerField(default=0)),
                ('forbidden', models.IntegerField(default=0)),
                ('forbidden_reason', models.TextField(default='')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_travels', to='utility.travelcollection')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_covers', to='utility.image')),
                ('images', models.ManyToManyField(related_name='travels', to='utility.image')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_records', to='utility.appuser')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_records', to='utility.appuser')),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_record', to='utility.address')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_travel_records', to='utility.schedule')),
                ('tag', models.ManyToManyField(related_name='tag_travel_records', to='utility.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('content', models.TextField(blank=True, default='', max_length=1000)),
                ('budget', models.FloatField(null=True)),
                ('real_consumption', models.FloatField(null=True)),
                ('if_alarm', models.IntegerField(default=0)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addr_schedule_item_records', to='utility.address')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='utility.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ReadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='utility.travelnotes')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('description', models.TextField(default='')),
                ('visibility', models.BooleanField(default=False)),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='utility.image')),
                ('images', models.ManyToManyField(related_name='position_owner', to='utility.image')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(default=0)),
                ('content', models.TextField(default=None, max_length=400, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='utility.appuser')),
                ('related_comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.comment')),
                ('related_companion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.companion')),
                ('related_flight', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.flight')),
                ('related_schedule_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.scheduleitem')),
                ('related_travel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.travelnotes')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.IntegerField()),
                ('target_id', models.IntegerField(default=None, null=True)),
                ('remarks', models.CharField(default='', max_length=48)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='utility.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='arrivalport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_flight_records', to='utility.port'),
        ),
        migrations.AddField(
            model_name='flight',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart_flight_records', to='utility.city'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart_flight_records', to='utility.port'),
        ),
        migrations.AddField(
            model_name='flight',
            name='endcity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_flight_records', to='utility.city'),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default=None, max_length=400, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages', to='utility.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='companion',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_companion_records', to='utility.schedule'),
        ),
        migrations.AddField(
            model_name='companion',
            name='tag',
            field=models.ManyToManyField(related_name='tag_companion_records', to='utility.tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='companion_master',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='utility.companion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to='utility.appuser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='master',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='utility.travelnotes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='utility.appuser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='utility.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursive_responses', to='utility.comment'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_province', to='utility.province'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='collection',
            field=models.ManyToManyField(related_name='collectors', to='utility.travelnotes'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='received_messages',
            field=models.ManyToManyField(related_name='target_users', to='utility.message'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subscription',
            field=models.ManyToManyField(related_name='subscribers', to='utility.appuser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='unread_messages',
            field=models.ManyToManyField(related_name='unread_users', to='utility.message'),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(default='', max_length=40)),
                ('content', models.TextField(default='')),
                ('url', models.URLField(default='')),
                ('action', models.TextField(default=None, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('read', models.PositiveIntegerField(default=0)),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_covers', to='utility.image')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses_city', to='utility.position'),
        ),
        migrations.AddField(
            model_name='address',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='utility.position'),
        ),
        migrations.AddField(
            model_name='address',
            name='province_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses_province', to='utility.position'),
        ),
    ]
