# Generated by Django 4.1.7 on 2023-04-04 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('introduce', models.TextField(null=True)),
                ('hot', models.FloatField(default=0.0)),
                ('grade', models.FloatField(default=5.0)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('playtime', models.FloatField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.address')),
                ('cover', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utility.image')),
            ],
        ),
        migrations.RenameModel(
            old_name='TravelCollection',
            new_name='TravelNotesCollection',
        ),
        migrations.AddField(
            model_name='appuser',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='utility.image'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='utility.address'),
        ),
        migrations.CreateModel(
            name='Subsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('introduce', models.TextField(null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.position')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.sight')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('type', models.SmallIntegerField(choices=[(0, '成人'), (1, '儿童'), (2, '学生'), (3, '老人')], default=0)),
                ('sight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.sight')),
                ('subsight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.subsight')),
            ],
        ),
    ]
