# Generated by Django 3.2.13 on 2023-03-31 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_scenic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('introduce', models.TextField(null=True)),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.scenic')),
            ],
        ),
    ]
