# Generated by Django 4.1.7 on 2023-04-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
