# Generated by Django 4.1.7 on 2023-04-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_remove_price_sight_remove_price_subsight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsight',
            name='sight',
        ),
    ]
