# Generated by Django 4.1.7 on 2023-04-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_remove_subsight_sight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='price_list',
        ),
        migrations.AddField(
            model_name='price',
            name='sight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.sight'),
        ),
        migrations.AddField(
            model_name='price',
            name='subsight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.subsight'),
        ),
        migrations.AddField(
            model_name='subsight',
            name='sight',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='utility.sight'),
            preserve_default=False,
        ),
    ]
