# Generated by Django 4.0.4 on 2022-05-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='content',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='travel',
            name='content',
            field=models.TextField(blank=True, default='', max_length=20000),
        ),
    ]
