# Generated by Django 4.0.4 on 2022-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_scheduleitem_content_alter_travel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShieldingWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
    ]
